# Generated by Django 5.1.1 on 2024-09-22 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_user_courses', to='workspace.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь курс',
                'verbose_name_plural': 'Пользователь курсы',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is_completed')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_user_lessons', to='workspace.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_user_lessons', to='progress.usercourse', verbose_name='Пользователь курс')),
            ],
            options={
                'verbose_name': 'Пользователь урок',
                'verbose_name_plural': 'Пользователь уроки',
            },
        ),
    ]
